---
name: CI

on:
  - pull_request
  - push

env:
  TESTOPT: "-v"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Ruby
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
    steps:
      - name: Install system dependencies
        run: sudo apt-get install imagemagick libmagickwand-dev
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install Ruby dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
